name: Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2022
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: ./build.ps1
        shell: pwsh
      - uses: actions/upload-artifact@v4
        with:
          name: BatteryStatus-Windows
          path: dist/
